### ISSUE TITLE
\xeCJKcaption{HUSTthesis}  undefined

### ISSUE THREAD

**Issue by fomy** [xiuliren/hustthesis#2]
我用的是 Tex Live 2015 套件，HUSTthesis.cls 会报错：

\xeCJKcaption{HUSTthesis} 没有定义

于是我注释这行，并将 HUSTthesis.cpx 的内容黏贴到 HUSTthesis.cls 尾部，错误消失

**Comment by xiuliren** [comment]
你可以试试把\xeCJKcaption换成input

2015-11-17 20:30 GMT-05:00 Min Fu notifications@github.com:

**Comment by fomy** [comment]
Thanks
